"""Update tables room, user, booking_bugfix

Revision ID: 50b566f97c50
Revises: dcd4b8bf9207
Create Date: 2023-09-03 17:18:29.479831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50b566f97c50'
down_revision: Union[str, None] = 'dcd4b8bf9207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f('ix_booking_price'),
        'booking',
        ['price'],
        unique=False
    )
    op.create_index(
        op.f('ix_hotel_location'),
        'hotel',
        ['location'],
        unique=False
    )
    op.alter_column(
        'room',
        'description',
        existing_type=sa.VARCHAR(),
        nullable=True
    )
    op.drop_constraint(
        'room_hotel_id_fkey',
        'room',
        type_='foreignkey')

    op.create_foreign_key(None, 'room', 'hotel', ['hotel_id'], ['id'], ondelete='cascade')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_constraint(None, 'room', type_='foreignkey')
    op.create_foreign_key(
        'room_hotel_id_fkey',
        'room',
        'hotel',
        ['hotel_id'],
        ['id']
    )
    op.alter_column('room', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_hotel_location'), table_name='hotel')
    op.drop_index(op.f('ix_booking_price'), table_name='booking')
    # ### end Alembic commands ###
